project_id = "iyqqpbvnszyrrgerniog"

[functions.admin-create-user]
verify_jwt = true

[functions.check-setup]
verify_jwt = false

[functions.create-member-user]
verify_jwt = true

[functions.create-owner]
verify_jwt = false

[functions.generate-fitness-plan]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false
